
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  server: #自我保护模式关闭 在注册中心会一直提示 很烦
    enable-self-preservation: false
  instance: #使用主机的IP地址来定义注册中心的地址
    prefer-ip-address: true

spring:
  application:
    name: eureka
server:
  port: 8761
